---
- hosts: mywebservers
  become: yes
  tasks:
    - name: Installing Java on Debian-based systems
      apt:
        name: "{{ myjavaforubuntu }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Installing Java on RedHat-based systems
      dnf:
        name: "{{ myjavaforredhat }}"
        state: present
      when: ansible_os_family == "RedHat"
