---
- hosts: 172.31.30.119
  become: yes
  tasks:
  - include_tasks: myfile.yml
  
  - name: install webserver
    apt:
      name: apache2
      state: present
  
  - name: I want to copy mytestfile to node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytest

  - name: I want to copy indexpage to node side
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restartwebserver

  - name: I want to download tomcat.
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.0-M1/bin/apache-tomcat-10.0.0-M1-fulldocs.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.0-M1-fulldocs.tar.gz
      force_basic_auth: yes
  
  handlers:
  - name: restartwebserver
    service:

