---
- hosts: 172.31.30.119
  become: yes
  tasks:
  - include_tasks: myfile.yml
  
  - name: install webserver
    apt:
      name: apache2
      state: present
  
  - name: I want to copy mytestfile to node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytest

