---
- name: My first playbook
  hosts: all
  become: yes

  tasks:
    - name: I want to install webserver
      apt:
        name: apache2
        state: present

    - name: I want to run webserver
      service:
        name: apache2
        state: started
