---
- name: My first playbook
  hosts: mywebservers
  become: yes
  gather_facts: yes

  tasks:
    - name: I want to install webserver
      apt:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"

    - name: I want to run webserver
      service:
        name: apache2
        state: started
      when: ansible_os_family=="Debian"
    
    - name: I want to install other server
      dnf:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"

    - name: I want to run other server
      service:
        name: httpd
        state: started
      when: ansible_os_family=="RedHat"



