---
- name: I want to start tomcat.
  systemd:
    daemon_reload: true
    state: started
    name: tomcat 
    enabled: true

- name: Allow port 8080 through UFW
  ufw:
    rule: allow
    port: 8080